name: Close issues when PRs are merged into `dev`

on:
  pull_request:
    types: [closed]
    branches:
      - dev

permissions:
  issues: write

jobs:
  close-linked-issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Close issues linked in PR
        uses: ldez/gha-mjolnir@v1.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
