name: Enforce Testing on PRs Against main
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  prepend-checklist:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main'
    steps:
      - name: Prepend checklist to PR body
        uses: devindford/pull-request-body-updater-github-action@v1.1.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          body-template: |
            ## Checklist
            - [ ] A version of the bot running this code has had at least one match reported successfully.
          body-update-action: prefix

  enforce-checked:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main'
    needs: prepend-checklist
    steps:
      - name: Validate checklist checked
        run: |
          body="${{ github.event.pull_request.body }}"
          if ! grep -q '\- \[x\] A version of the bot running this code' <<< "$body"; then
            echo "You must check the checklist before merging." >&2
            exit 1
          fi
