name: Enforce Testing on PRs Against main
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  update-and-enforce:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main'
    steps:
      - name: Check and update PR body
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || '';
            const checklist = `## Checklist - [ ] A version of the bot running this code has had at least one match reported successfully.`;

            let newBody = body;
            if (!body.includes("A version of the bot running this code")) {
              newBody = `${checklist}\n\n${body}`;
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                body: newBody,
              });
            }

            if (!newBody.includes("- [x] A version of the bot running this code")) {
              core.setFailed("Checklist must be checked before merging.");
            }
